### ISSUE TITLE
The transaction count (Yes/No) shows transactions that ended with 'throw'

### ISSUE THREAD

**Issue by jo-tud** [slockit/dao-dapp#7]
At first I want to say that it's great someone is developing a dApp for voting and looking at proposals.

I found this issue when I was counting voting transactions for another project. 
Your code needs to filter out transactions that have thrown. E.g. for proposal 5 there are actually 887 yes transactions and not 994. My analysis shows that there were 107 YES-calls to the vote function returning an error. This adds up to the 994 you are currently showing.
A side note: delegate votes are also not considered.

**Comment by simon-jentzsch** [comment]
Thanks, I agree this is a bug. I just fixed it. So now I ignore all Transactions that throw (having gas=gasUsed)
